### ISSUE TITLE
not supported error

### ISSUE THREAD

**Issue by rushins** [Marcus-Smallman/csharp-kestrel-mongo#1]
i am getting this error.

faas-cli new mongo-function --lang csharp-kestrel-mongo
Csharp-kestrel-mongo is unavailable or not supported

**Comment by marcus-smallman-lewis** [comment]
You tend to see this error when the referenced template, so in this case 'csharp-kestrel-mongo', has not been downloaded.

Make sure you have executed:
**`faas-cli template pull https://github.com/Marcus-Smallman/csharp-kestrel-mongo.git`**
before running:
**`faas-cli new mongo-function --lang csharp-kestrel-mongo`**

**Comment by rushins** [comment]
yes worked but i dont see any data . you did mentioned on your blog https://marcussmallman.io/2018/11/27/net-core-openfaas-mongodb/#comment-9? how do you see data in function within openfaas serverless
---------------------------------------------
Data can then be sent via the request body to the function as seen in the screen shot above. This will then, if successful, return your given input and a status code of 201.

We can also prove that the data has been written to our MongoDB by using a MongoDB client to connect to our MongoDB and check that the data has been stored:

----------------------------------------

**Comment by marcus-smallman-lewis** [comment]
Well it is up to you how you want to view the data.

For the purpose of the blog post I used a MongoDB client to interact with the database directly to see that the data had been stored.

What you could do is create another function called 'get-data' that returns all the data in your MongoDB. This can be achieved by using the **csharp-kestrel-mongo** template.
Documentation on how to utilize the C# MongoDB client in the function can be found in the MongoDB docs.

I will close this issue now as it appears you have solved your initial issue.
